### ISSUE TITLE
Native addons aren't working

### ISSUE THREAD

**Issue by kgunnar** [slee047/node-packer#8]
Hi @slee047,

I've tried building a Node.js app that makes use of a node-gyp native module but it generates an error when running the packed binary:

```
internal/modules/cjs/loader.js:730
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /__enclose_io_memfs__/binding.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/__enclose_io_memfs__/index.js:1:76)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
```
The binary grows in size when including the binding.node file and reference to it, so it seems to be including it in the executable but it can't use it for some reason. If I rebuild the node-gyp addon for Node.js 8, I can package the binary with pmq20's original version and that does work. But it would be really nice to get Node.js 10 working with your fork.

Even building a binding.node with the node-gyp "hello world" sample (https://github.com/nodejs/node/tree/master/test/addons/hello-world) has this same issue.

**Comment by slee047** [comment]
Hi, thanks for writing in. Luck is on your side as I have also realized this issue when compiling some Node.js application that calls sqlite3. 

I should have fixed this issue with the new release below:
https://github.com/slee047/node-packer/releases/tag/1.6.0-10.15.3-1

This issue does not apply to Node.js 8 (All Series 8 releases, including 8.16.0) because the folder **node-packer/node/lib/internal/modules/cjs** don't exist in Node.js 8.

In essence, it means that there was 1 point of entry I have failed to hack it when I tried to transit node-packer to use Node.js 10.

**Comment by kgunnar** [comment]
Thanks! Confirmed it works now for me as well.

In case anyone pulls this and still has the same issue: make sure you at least initially run with "--clean-tmpdir" to rebuild the included Node.js. I did not think to do it at first and it was using what was there from 1.6.0-10.15.3 which made it look like the problem was not resolved even though it was.
